name: "Bug Report"
description: "Report a bug to help us identify and fix issues."
type: "Bug"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: "Describe the Bug"
      description: "What happened, and what did you expect instead?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain the problem."
