name: "Story"
description: "Create a user story issue to describe a feature or enhancement from the user's perspective."
type: "Feature"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "User Story"
      value: |
        As a [type of user], I want [goal], so that [benefit].

        **Scenarios:**

        Given [precondition],
        When [action],
        Then [expected result].
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Acceptance Criteria"
      value: |
        - [ ] First criteria

